# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normal
ncpus: 1440
jobfs: 10GB
mem: 5760GB

walltime: 10:00:00
jobname: epbl_Reichl_2024

model: access-om3

exe: access-om3-MOM6-CICE6
input:
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/access-om2-025deg-ESMFmesh.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/access-om2-025deg-nomask-ESMFmesh.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/topog.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/ocean_hgrid.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/ocean_vgrid.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/ocean_temp_salt.res.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/salt_sfc_restore.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/grid.nc
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/New_grid_input_files_025deg_75zlevels/kmt.nc
- /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
- /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
- /g/data/vk83/experiments/inputs/JRA-55/RYF/v1-4/data
- /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/EM_new_structure/rof_remap_weights.nc

collate: false
runlog: false
metadata:
  enable: true

userscripts:
  setup: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/setup.sh
  archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh

# modules:
#   use:
#   - /g/data/vk83/prerelease/modules
#   load:                                                                                                                                                                                                                                                                                                                                                                                         
#   - access-om3/pr42-2
#   - nco/5.0.5

modules:
  use: 
    - /g/data/tm70/ml0072/COMMON/git_repos/spack/0.22/release/modules/linux-rocky8-x86_64
  load:
   - access-om3-bug-fix/2025.01.0

payu_minimum_version: 1.1.6
restart_freq: 1

restart: /g/data/tm70/ml0072/COMMON/git_repos/COSIMA_om3-scripts/expts_manager/EM_new_structure/product1_0.25deg_new_topo_ezhil_update/epbl_Reichl_2024_2/archive/restart006
